### ISSUE TITLE
Windows: quoted arguments containing spaces are processed incorrectly

### ISSUE THREAD

**Issue by stys** [ForbesLindesay/win-spawn#10]
I believe Node's original `spawn` escapes quotes in arguments, so `"\"value with spaces\""` is passed as `\"value with spaces\"` to cmd. It is not possible to produce correctly quoted arguments such as descibed in this SO answer http://stackoverflow.com/a/12892791/1703316.

It can be fixed by adding `windowsVerbatimArguments: true` to the options of the `cSpawn`

**Comment by ForbesLindesay** [comment]
This module is now deprecated (see readme)
