### ISSUE TITLE
Using ctrl+c kill the process fails

### ISSUE THREAD

**Issue by zhangmeng712** [ForbesLindesay/win-spawn#11]
I use the win-spawn to call grunt, like 
win-spawn('grunt', '--live') ...
when I run in git-bash in windows , it worked perfectly , however when I kill the process by Ctrl+C
The git bash did not respond and always show the tips like the “终止批处理操作吗（Y/N）”
I don't know what's going wrong ? Have you ever seen the situation before?
Is there any method to kill the process friendly?

**Comment by ForbesLindesay** [comment]
This module is now deprecated (see readme)
