### ISSUE TITLE
Usage in scripts

### ISSUE THREAD

**Issue by kentcdodds** [ForbesLindesay/win-spawn#13]
Maybe I'm misunderstanding this module, but my assumption is that I can use this to make my `package.json` scripts work cross-platform when setting environment variables. Is this true?

I have set up an example repo with [scripts](https://github.com/kentcdodds/win-spawn-scripts/blob/master/package.json#L6-L9) to show what I'm experiencing.

Here are the scripts:

```javascript
"scripts": {
  "test:win-spawn": "win-spawn FOO=bar && echo $FOO",
  "test:no-win-spawn": "FOO=bar && echo $FOO"
},
```

Here's what happens when I run them:

```
~/Desktop/win-spawn-scripts (master)
⛄  $ npm run test:win-spawn -s
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: spawn FOO=bar undefined ENOENT
    at exports._errnoException (util.js:814:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
    at Function.Module.runMain (module.js:473:11)
    at startup (node.js:117:18)
    at node.js:948:3
~/Desktop/win-spawn-scripts (master)
⛄  $ npm run test:no-win-spawn -s
bar
```

Am I doing things wrong in the `test:win-spawn`?

**Comment by sheerun** [comment]
It's because win-spawn leaves env variables intact for non-windows enviroment, and uses spawn instead of bash. It makes this package unusable on both platforms at once.

**Comment by kentcdodds** [comment]
Ah, understood. I no longer have a use case for this module. You can feel free to close this.

**Comment by sheerun** [comment]
@kentcdodds What do you use instead?

**Comment by kentcdodds** [comment]
I pretty much only needed to have a way to set environment variables in npm scripts so I created [cross-env](http://npm.im/cross-env) which didn't work out, so I made [argv-set-env](http://npm.im/argv-set-env). Someone made a PR to `cross-env` so I think that's working now :-)

**Comment by sheerun** [comment]
That's what i've searched for. Thank you :)

**Comment by ForbesLindesay** [comment]
This module is now deprecated (see readme)
