### ISSUE TITLE
Use of cmd.exe makes it impossible to control spawned process

### ISSUE THREAD

**Issue by arobson** [ForbesLindesay/win-spawn#8]
It's possible that I don't fully understand the reasons/nuances for running the target via cmd.exe as a proxy, but it does have an extremely detrimental effect: you can't (programmatically) kill a process started this way. The PID reported back to Node is the PID of the cmd.exe and __not__ the PID of the actual target. Because you can't get the correct PID, you have no control over the process :cry:.

Thanks for this library!

**Comment by ForbesLindesay** [comment]
This module is now deprecated (see readme)
